# Семинар по numpy

В этом семинаре мы познакомимся с первой библиотекой, которая понадобится нам в курсе - библиотекой numpy. Это библиотека для работы с матрицами, и она может быть также полезна для матричных вычислений в других дисциплинах. Но сначала познакомимся с интерфейсом jupyter notebook. Это инструмент, позволяющий писать код в интерактивном режиме, рисовать графики и оформлять материалы.

## Очень краткий обзор интерфейса jupyter notebook
Jupyter notebook состоит из ячеек.
В ячейку можно записывать код, выполнять, а потом использовать созданные переменные / определенные функции и т. д. в других ячейках:

In [1]:
x = [1, 2, 3]

In [2]:
print(x)

[1, 2, 3]


In [3]:
x = 9

In [4]:
y = 3

Выполнить ячейку: shift + enter, показать аргументы функции: shift + tab. Есть много других горячих клавиш, см. Help -> Keyboard Shortcuts (вверху интерфейса). Там же есть Help -> User Interface Tool!

Обратите внимание на кнопки + (добавить ячейку), ножницы (удалить ячейку), стрелки, меняющие ячейки местами, кнопку остановить выполнение.

Ноутбук сохраняется автоматически. Чтобы скачать: File -> Download as -> ipynb.

Этот текст написан в ячейке типа Markdown, она позволяет красиво оформлять код. Переключение типа ячейки справа от кнопки стоп (черный квадрат). Ячейки с кодом имеют тип Code.

## Создание массивов в numpy

Numpy - библиотека для работы с матрицами. Импортируем библиотеку:

In [5]:
import numpy as np

Предположим, что мы провели опрос, в котором было четыре вопроса, на каждый можно ответить Да, Нет, Воздержался. В итоге получим таблицу размера 4 на 3. Создадим такую таблицу в numpy:

In [6]:
l = [[30, 2, 0], [3, 27, 1], [28, 1, 1], [6, 17, 5]]
ar = np.array(l)

In [7]:
ar # выводится созданное в последней строке, если в ней нет присваивания (знак =)

array([[30,  2,  0],
       [ 3, 27,  1],
       [28,  1,  1],
       [ 6, 17,  5]])

Можно создавать массивы из нулей (np.zeros) или из единиц (np.ones):

In [8]:
A = np.ones((7, 9))

Также часто используется создание векторов из натуральных чисел:

In [9]:
vec = np.arange(15)

И случайно сгенерированные массивы:

In [10]:
r = np.random.rand(3, 4)
r

array([[0.21417819, 0.22451127, 0.41608438, 0.72657586],
       [0.94949148, 0.23103028, 0.6728598 , 0.34397972],
       [0.56382628, 0.69711696, 0.91459594, 0.40149763]])

### Размерности массивов

Размерности:

In [11]:
ar.shape

(4, 3)

In [12]:
A.shape

(7, 9)

In [13]:
vec.shape

(15,)

В numpy нулевая размерность отвечает за строки, первая - за столбцы. В нашей матрице ar 4 строки и 3 столбца. Вообще в numpy можно создавать массивы любых размерностей точно таким же образом, как мы сделали выше - numpy не различает векторы, матрицы и тензоры, все они называются массивами. Например, vec имеет длину 15 только по одной размерности, поэтому его shape равен (15,). Shape - это обычный кортеж языка python.

Можно вытянуть все ответы в одну строку:

In [14]:
ar.ravel()

array([30,  2,  0,  3, 27,  1, 28,  1,  1,  6, 17,  5])

Можно наоборот: преобразовать вектор в матрицу:

In [15]:
vec.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Обратите внимание, что числа записываются по строкам.

In [16]:
vec.reshape(3, 5).shape

(3, 5)

По одной из осей можно указывать -1, тогда библиотека сама посчитает число элементов по этой размерности:

In [17]:
vec.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Аналогичным образом можно дублироать функционал функции ravel:

In [18]:
vec.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Операции с массивами

Можно выделить три группы операций с массивами в numpy:
* поэлементные
* матричные
* агрегирующие

Поэлементные выполняются между массивами одной формы (shape), хотя ниже мы обсудим некое обощение правила одной формы.

In [19]:
vec + vec

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [20]:
A * 10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [21]:
x = np.array([1, 2, 3])
y = np.array([-1, 1, -1])
x * y

array([-1,  2, -3])

Обратите внимание, что * - это поэлементное умножение, а не матричное!

In [22]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

Матричные операции - операции из линейной алгебры. Например, матричное произведение:

In [23]:
A = np.random.rand(7, 8)
B = np.random.rand(8, 3)
A.dot(B)

array([[2.56769798, 2.15063502, 1.60428366],
       [3.62939763, 3.7041103 , 2.82874172],
       [2.71921625, 2.56463355, 1.7077891 ],
       [2.43597166, 2.09944891, 1.51872568],
       [2.60284682, 2.33517331, 1.71868554],
       [3.11382917, 2.93232948, 2.12910174],
       [1.69334844, 1.82220207, 1.65747254]])

Можно писать и так:

In [24]:
np.dot(A, B)

array([[2.56769798, 2.15063502, 1.60428366],
       [3.62939763, 3.7041103 , 2.82874172],
       [2.71921625, 2.56463355, 1.7077891 ],
       [2.43597166, 2.09944891, 1.51872568],
       [2.60284682, 2.33517331, 1.71868554],
       [3.11382917, 2.93232948, 2.12910174],
       [1.69334844, 1.82220207, 1.65747254]])

И так:

In [25]:
A @ B

array([[2.56769798, 2.15063502, 1.60428366],
       [3.62939763, 3.7041103 , 2.82874172],
       [2.71921625, 2.56463355, 1.7077891 ],
       [2.43597166, 2.09944891, 1.51872568],
       [2.60284682, 2.33517331, 1.71868554],
       [3.11382917, 2.93232948, 2.12910174],
       [1.69334844, 1.82220207, 1.65747254]])

Проверим форму:

In [26]:
A.dot(B).shape

(7, 3)

Обращение матрицы:

In [27]:
np.linalg.inv(np.random.rand(3, 3))

array([[ 3.10907751, -0.08672495, -0.70225495],
       [ 0.41275328, -1.74501659,  1.86030273],
       [-2.32138505,  1.63513765,  0.12644902]])

Модуль np.linalg содержит много полезных матричных функций, их можно посмотреть в документации модуля.

 Агрегирующие операции агрерируют информацию в троках, столбцах, во всем массиве и т. д. Самые популярные такие операции - суммирование np.sum, усреднение np.mean, медиана np.median, максимум np.max и минимум np.min.

Число полученных ответов на вопросы (всего): 

In [28]:
np.sum(ar)

np.int64(121)

Пробуем выяснить число респондентов. Для этого просуммируем матрицу по строкам (это делается с помощью указания axis=1):

In [29]:
np.sum(ar, axis = 1) 

array([32, 31, 30, 28])

In [30]:
np.sum(ar, axis = 1).shape

(4,)

По столбцам: axis=0, по строкам: axis=1.

В результате суммирования получился вектор (размерность на 1 меньше, чем у исходной матрицы). Можно указать keepdims=True, чтобы сохранть размерности:

In [31]:
np.sum(ar, axis = 1, keepdims=True).shape

(4, 1)

Задание для студентов: посчитать сумму по строкам, используя матричное произведение.

In [32]:
# student's code here

Считаем число ответов "да", "нет", "воздержался" двумя способами:

In [33]:
np.sum(ar, axis=0)

array([67, 47,  7])

In [34]:
ones = np.ones(4)

In [35]:
np.dot(ones, ar)

array([67., 47.,  7.])

### Индексация
Для индексации ставим [ ] и через запятую перечисляем действия с осями. В матрице 0 - по вертикали, 1 - по горизонтали

In [36]:
ar[2, 1] # выбрать 1 элемент

np.int64(1)

In [37]:
ar # вывели для проверки

array([[30,  2,  0],
       [ 3, 27,  1],
       [28,  1,  1],
       [ 6, 17,  5]])

In [38]:
ar[:, 2] # выделить столбец

array([0, 1, 1, 5])

In [39]:
ar[:, -1] # выделить последний столбец

array([0, 1, 1, 5])

In [40]:
ar[1] # выделить строку

array([ 3, 27,  1])

In [41]:
ar[:, ::2] # выделить все столбы с четными номерами

array([[30,  0],
       [ 3,  1],
       [28,  1],
       [ 6,  5]])

 Можно делать логическую индексацию, чтобы выбирались только те элементы, для которых стоит True. Выберем ответы на вопросы с номерами, кратными 2: 

In [42]:
 ar[np.arange(ar.shape[0])%2==0]

array([[30,  2,  0],
       [28,  1,  1]])

### Добавление оси

Для удобного перехода между размерностями используют добавление оси. Вектор можно сделать матрицей с размером 1 по одной из размерностей.

In [43]:
ones[:, np.newaxis]

array([[1.],
       [1.],
       [1.],
       [1.]])

In [44]:
ones[:, np.newaxis].shape 
# вместо вектора с формой (4,) стала матрциа с формой (4, 1)

(4, 1)

In [45]:
ones[np.newaxis, :]
# вместо вектора с формой (4,) стала матрциа с формой (1, 4)

array([[1., 1., 1., 1.]])

In [46]:
ones[np.newaxis, :].shape

(1, 4)

### Добавление оси в поэлементных операциях

В поэлементных операциях можно использовать не только массивы в одинаковым в точности размером. В общем виде условие такое: по каждой размерности либо размер совпадает, либо в одном из массивов размер 1. Например, матрица размера (4, 3) и вектор размера (4, 1). В этом случае при выполнении операции столбец будет как бы "дублироваться" для каждого столбца в первой матрице. Воспользуемся этим, чтобы найти долю каждого ответа на все вопросы:

In [47]:
sums = ar.sum(axis=1) # всего ответов на каждый вопрос
sums.shape

(4,)

In [48]:
sums[:, np.newaxis].shape # добавили ось

(4, 1)

In [49]:
ar / sums[:, np.newaxis] # поделили число каждого варианта на общее число ответов на вопрос

array([[0.9375    , 0.0625    , 0.        ],
       [0.09677419, 0.87096774, 0.03225806],
       [0.93333333, 0.03333333, 0.03333333],
       [0.21428571, 0.60714286, 0.17857143]])

### Объединение массивов

Добавляем новый вопрос в таблицу:

In [50]:
row = np.array([5, 12, 15])
row = row[np.newaxis, :] 
# конкретно тут можно без увеличения размерности
# но в других случаях может быть ошибка, лучше добавлять
ar = np.vstack((ar, row))

Добавляем новый столбец в таблицу - максимальное число ответов:

In [51]:
mx = np.max(ar, 1)
mx

array([30, 27, 28, 17, 15])

In [52]:
mx.shape

(5,)

In [53]:
mx = mx[:, np.newaxis]

In [54]:
ar = np.hstack ((ar, mx))
ar

array([[30,  2,  0, 30],
       [ 3, 27,  1, 27],
       [28,  1,  1, 28],
       [ 6, 17,  5, 17],
       [ 5, 12, 15, 15]])

Удаление строки (аналогично можно удалять столбец):

In [55]:
np.delete(ar, np.arange(3, 5), axis=0)

array([[30,  2,  0, 30],
       [ 3, 27,  1, 27],
       [28,  1,  1, 28]])

### Задания для студентов

Выделите строки, у которых ответов "нет" больше, чем ответов "да":

In [56]:
# student's code here


Вывести квадраты первых десяти натуральных чисел:

In [57]:
# student's code here


Перемешать числа натуральные числа от 1 до 10 (воспользуйтесь np.random.permutation):

In [58]:
# помощь по функции
?np.random.permutation

Signature: np.random.permutation(x)
Docstring:
permutation(x)

Randomly permute a sequence, or return a permuted range.

If `x` is a multi-dimensional array, it is only shuffled along its
first index.

.. note::
    New code should use the
    `~numpy.random.Generator.permutation`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : int or array_like
    If `x` is an integer, randomly permute ``np.arange(x)``.
    If `x` is an array, make a copy and shuffle the elements
    randomly.

Returns
-------
out : ndarray
    Permuted sequence or array range.

See Also
--------
random.Generator.permutation: which should be used for new code.

Examples
--------
>>> np.random.permutation(10)
array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6]) # random

>>> np.random.permutation([1, 4, 9, 12, 15])
array([15,  1,  9,  4, 12]) # random

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.permutation(arr)
array([[6, 7, 8], # random
 

In [59]:
# student's code here


Составить таблицу умножения от 1 до 10:

In [60]:
# student's code here
